source("load.R")
setwd("C:/Sammy/ExData_Plotting1")
df2 <- mutate(df1,datetime = as.POSIXct(strptime(paste(date,time,sep=" "),"%Y-%m-%d %H:%M:%S")))
png(file="plot3.png",height = 480, width = 480, units = "px")
with(df2,plot(datetime,Sub_metering_1,type = "n"))
with(df2,lines(datetime,Sub_metering_1,col="black"))
with(df2,lines(datetime,Sub_metering_2,col="red"))
with(df2,lines(datetime,Sub_metering_3,col="blue"))
dev.off()